### ISSUE TITLE
Accumulate logs on debug tab

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/eth-node-status-page#18]
Currently RPC returns only 128 last entries.
When user has the debug page open we should accumulate the entries (up to some memory-acceptable value)

**Comment by Adam-Goldman7** [comment]
this is done right?

we have `renderLogs` on debug page

**Comment by tomusdrw** [comment]
Nope - we are displaying only what's returned from RPC (meaning only last 128 entries).
We can use a bit more memory in client and store let say 1024 entries when you look on debug page.
So it means that we need to detect newly added logs by comparing what we have and what RPC returned previously.

Other option might be changing implementation on parity side to have "filter object".

**Comment by Adam-Goldman7** [comment]
save  1024 entries to LS?

**Comment by tomusdrw** [comment]
It's enough to just keep them in memory (state).

**Comment by Adam-Goldman7** [comment]
maybe the simplest solution from parity perspective would b to pass a timestamp/date
as in "gimmie all logs that happened after ___"

I dont know much about parity internals, just that polling all logs on every tick sounds heavy

actually maybe this is something we can generalize on parity's side?

for example instead of getting all accounts on every tick, we check for if it changed since last tick, and only if it has we fetch accounts again

thoughts?

**Comment by Adam-Goldman7** [comment]
also I can work on this issue if u gimmie some guidance on how to generate logs
I c only 4 log entries every time

**Comment by tomusdrw** [comment]
Just run parity with `-l sync=trace` or `-l miner=trace` you will get a shitload of logs:)

**Comment by tomusdrw** [comment]
Regarding the polling since last tick: 
This is exactly how filters work in JSON-RPC:
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
filters for logs are not implemented though.
